### PR TITLE
Move dummy artifact plugin over

### PR DESCRIPTION
**Pull request by arvindsv**
##### 2. Verify by checking contents:

```bash
# OLD
$ git clone https://github.com/bdpiparva/dummy-artifact-plugin

$ ./gradlew clean test assemble

$ unzip -lv build/libs/dummy-artifact-plugin-0.0.1.jar >/tmp/old.dummy.txt

$ unzip -lv build/libs/dummy-artifact-plugin-0.0.1.jar | sort -k7 | cut -c49- >/tmp/old.dummy.shortened.txt
```

```bash
# NEW (see instructions in #67)
$ ./gradlew clean test assemble copyJarsToOnePlace -PgoVersion=18.10.0-26429

$ unzip -lv target/go-plugins-dist/dummy-artifact-plugin.jar >/tmp/new.dummy.txt

$ unzip -lv target/go-plugins-dist/dummy-artifact-plugin.jar | sort -k7 | cut -c49- >/tmp/new.dummy.shortened.txt
```

##### 3. Compare:

```diff
$ diff /tmp/old.dummy.shortened.txt /tmp/new.dummy.shortened.txt
3c3
< .jar
---
> plugin.jar
24a25
> 325fd6bc  META-INF/MANIFEST.MF
54d54
< ee027fb2  META-INF/MANIFEST.MF
```

### CODE REVIEW

**Comment by arvindsv** [comment]
@rajiesh Do you think this is ok to merge? I'm planning to merge #5188 soon and this is one of the tasks in it.

**Comment by rajiesh** [comment]
@arvindsv currently the test plugin for external artifacts is moved to gocd-contrib https://github.com/gocd-contrib/test-external-artifacts-plugin. Do we need to move it here?

**Comment by arvindsv** [comment]
@rajiesh Aren't all other test plugins in this repo [(here)](https://github.com/gocd/go-plugins/tree/master/plugins-for-tests)? What is special about the artifacts one, that it needs to be outside? Or, maybe it was based on some conversation I wasn't in?

**Comment by arvindsv** [comment]
Also, I don't see it being built, as a part of the plugins pipeline in build.gocd.org.

**Comment by rajiesh** [comment]
@arvindsv gocd-contrib has all the skeleton plugins. I thought this can also be used as reference implementation for external artifacts plugin and so moved it here. Am fine with moving it into go-plugins

**Comment by arvindsv** [comment]
Ok, I'm merging this. I think a proper reference/skeleton plugin needs to be written for this endpoint, as with the [other skeleton plugins](https://github.com/gocd-contrib/?utf8=✓&q=skeleton). This current plugin takes a lot of shortcuts and is not ideal as a skeleton, I feel.

Let's come up with a different one. For now, let's have this as a test plugin. Maybe we can rename https://github.com/gocd-contrib/test-external-artifacts-plugin to https://github.com/gocd-contrib/test-external-artifacts-plugin https://github.com/gocd-contrib/artifacts-skeleton-plugin and modify it to make it easier for people to start with?

**Pull request merged**
